/**
 * Demo fixture data — generated by scripts/demo-snapshot.ts.
 * Serves all API responses for demo mode users.
 *
 * Keys are API paths without the /api/ prefix.
 * The catch-all route joins the [...path] segments and looks up here.
 */

/** The date this snapshot was captured. Used for date-shifting. */
export const SNAPSHOT_DATE = "2026-04-14";

/** Settings fixture — includes demo: true flag and full profile. */
export const settingsFixture = {
  demo: true,
  email: "demo@springa.run",
  raceDate: "2026-06-13",
  raceName: "EcoTrail Stockholm 16K",
  raceDist: 16,
  totalWeeks: 24,
  startKm: 8,
  currentAbilitySecs: 1620,
  currentAbilityDist: 5,
  diabetesMode: true,
  onboardingComplete: true,
  displayName: "Alex",
  timezone: "Europe/Stockholm",
  runDays: [1, 3, 6, 0],
  longRunDay: 0,
  insulinType: "fiasp",
  intervalsConnected: true,
  nightscoutConnected: true,
  nightscoutUrl: "https://demo.springa.run",
  lthr: 165,
  maxHr: 192,
  hrZones: [134, 153, 163, 172, 182],
  restingHr: 52,
  sportSettingsId: 1,
  includeBasePhase: false,
  warmthPreference: 0,
  widgetOrder: null,
  hiddenWidgets: null,
  bgChartWindow: 180,
};

/** BG readings fixture — last 24h of CGM data. */
export const bgFixture = {
  readings: [
    { mmol: 6.2, sgv: 112, ts: -3600000, direction: "Flat" },
    { mmol: 6.5, sgv: 117, ts: -3300000, direction: "Flat" },
    { mmol: 6.8, sgv: 122, ts: -3000000, direction: "FortyFiveUp" },
    { mmol: 7.0, sgv: 126, ts: -2700000, direction: "Flat" },
    { mmol: 6.7, sgv: 121, ts: -2400000, direction: "FortyFiveDown" },
    { mmol: 6.4, sgv: 115, ts: -2100000, direction: "Flat" },
    { mmol: 6.2, sgv: 112, ts: -1800000, direction: "Flat" },
    { mmol: 6.0, sgv: 108, ts: -1500000, direction: "Flat" },
    { mmol: 5.9, sgv: 106, ts: -1200000, direction: "Flat" },
    { mmol: 6.1, sgv: 110, ts: -900000, direction: "FortyFiveUp" },
    { mmol: 6.3, sgv: 113, ts: -600000, direction: "Flat" },
    { mmol: 6.2, sgv: 112, ts: -300000, direction: "Flat" },
  ],
  current: {
    mmol: 6.2,
    sgv: 112,
    ts: -300000,
    direction: "Flat",
    arrow: "\u2192",
  },
  trend: {
    slope: -0.002,
    direction: "Flat",
    arrow: "\u2192",
  },
};

/** Calendar events fixture — planned + completed workouts. */
export const calendarFixture: unknown[] = [];

/** Wellness fixture — ATL/CTL/TSB. */
export const wellnessFixture: unknown[] = [];

/** Pace curves fixture. */
export const paceCurvesFixture = { bestEfforts: [] };

/** IOB fixture. */
export const insulinContextFixture = { iob: 0.8, updated: -300000 };

/** BG cache (model) fixture. */
export const bgCacheFixture = {};

/** BG patterns fixture. */
export const bgPatternsFixture = { patternsText: null };

/** Activity fixtures keyed by activity ID. */
export const activityFixtures: Record<string, unknown> = {};

/** Stream fixtures keyed by activity ID. */
export const streamFixtures: Record<string, unknown> = {};

/** Canned coach responses keyed by exact question text. */
export const coachFixtures: Record<string, string> = {
  "What can Springa do for me?":
    "Springa is your AI-powered training companion designed specifically for runners managing Type 1 diabetes. Here's what I can help with:\n\n**Training Plan Generation** — I create periodized plans that progress from your current fitness to your race goal (EcoTrail Stockholm 16K). Each week's workouts are structured with the right mix of easy runs, long runs, and speed work.\n\n**Blood Glucose Management** — During runs, I track your BG response to different workout types and fuel rates. The BG model learns from your data to recommend fuel rates that keep you stable.\n\n**Fuel Rate Optimization** — Based on your completed runs, I analyze how different carb intake rates affect your BG. The model suggests adjustments so you can run without worrying about lows or post-run spikes.\n\n**AI Coaching** — Ask me anything about your training, recovery, BG trends, or upcoming workouts. I have full context on your plan, recent runs, and physiological data.\n\n**Race Readiness** — I track your fitness (CTL), fatigue (ATL), and freshness (TSB) to tell you how you're tracking toward race day.",
};

/**
 * Fixture lookup map — keyed by API path (without /api/ prefix).
 * The catch-all route joins [...path] segments and looks up here.
 */
export const fixtures: Record<string, unknown> = {
  settings: settingsFixture,
  bg: bgFixture,
  "intervals/calendar": calendarFixture,
  wellness: wellnessFixture,
  "intervals/pace-curves": paceCurvesFixture,
  "insulin-context": insulinContextFixture,
  "bg-cache": bgCacheFixture,
  "bg-patterns": bgPatternsFixture,
};
